--Creación de la View y trae los alquileres del día que se consulta. A la 00.01 hs esta consulta se ve vacía debido a que todos los artículos, mediante el SP_HABILITA_ESCALA se vuelven a habilitar.
Create View AlquileresXPuesto AS (  
SELECT  
 1 AS [Cantidad],  
    STA11.COD_ARTICU AS [Cód. Artículo],  
    STA11.DESCRIPCIO AS [Desc. Artículo],   
    STA11FLD.DESCRIP AS [Puesto]  
FROM   
    STA11   
JOIN   
    STA11ITC ON STA11.COD_ARTICU = STA11ITC.CODEA  
JOIN   
    STA11FLD ON STA11ITC.IDFOLDER = STA11FLD.IDFOLDER  
WHERE   
    PERFIL = 'N'  
    AND (  
		STA11.COD_ARTICU LIKE 'LCKG01%'
		OR STA11.COD_ARTICU LIKE 'LCKC01%'
		OR STA11.COD_ARTICU LIKE 'VSOM01%'
		OR STA11.COD_ARTICU LIKE 'VMCL01%'
		OR STA11.COD_ARTICU LIKE 'AMSOM1%'
		OR STA11.COD_ARTICU LIKE 'AMMSL1%'
		OR STA11.COD_ARTICU LIKE 'AMMCL1%'
		OR STA11.COD_ARTICU LIKE 'AZSOM1%'
		OR STA11.COD_ARTICU LIKE 'AZMSL1%'
		OR STA11.COD_ARTICU LIKE 'AZMCL1%'
		OR STA11.COD_ARTICU LIKE 'MMSL01%'
		OR STA11.COD_ARTICU LIKE 'MMCL01%'
		OR STA11.COD_ARTICU LIKE 'MSOM01%'
		OR STA11.COD_ARTICU LIKE 'NMCL01%'
		OR STA11.COD_ARTICU LIKE 'NSOM01%'
		OR STA11.COD_ARTICU LIKE 'CMT001%'
		OR STA11.COD_ARTICU LIKE 'NMSL01%'
    )  
GROUP BY   
    STA11FLD.DESCRIP,   
    STA11.COD_ARTICU,   
    STA11.DESCRIPCIO  
)  
