--Se ejecuta la vista creada
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET DATEFORMAT DMY 
SET DATEFIRST 7 
SET DEADLOCK_PRIORITY -8;
Select * from MedioPagoXPuesto


--Se crea la vista Ventas por Medio de Pago agregando el Puesto correspondiente.
CREATE View MedioPagoXPuesto AS (
SELECT 
	ISNULL(SBA01.COD_CTA, ' ') AS [Cód. de Cuenta] ,
	SBA01.DESCRIPCIO AS [Desc. cuenta] ,
	VENTA.FECHA_EMIS AS [Fecha de Emisión],
	CASE WHEN VENTA.TIPO = 'CONTADO' AND SBA01.TIPO = 'O' THEN 'Efectivo' WHEN VENTA.TIPO = 'CONTADO' AND SBA01.TIPO = 'T' THEN 'Tarjeta' WHEN VENTA.TIPO = 'CONTADO' AND SBA01.TIPO = 'C' THEN 'Cheque de Terceros' WHEN VENTA.TIPO = 'CONTADO' AND SBA01.TIPO = 'B' THEN 'Bancos' WHEN VENTA.TIPO = 'CTACTE' THEN 'Cuenta Corriente' END AS [Medio de Pago] ,
	CASE WHEN VENTA.TIPO = 'CONTADO' THEN 'Venta al Contado' WHEN VENTA.TIPO = 'CTACTE' THEN 'Venta en Cuenta Corriente' END AS [Condición de Venta] ,
	SUM(CASE WHEN VENTA.TIPO = 'CONTADO' THEN CASE SBA05.D_H WHEN 'D' THEN ISNULL(SBA05.MONTO, 0) ELSE -1 * ISNULL(SBA05.MONTO,0) END ELSE CASE VENTA.TCOMP_IN_V WHEN 'CC' THEN (-1 * VENTA.IMPORTE)	ELSE VENTA.IMPORTE END END) AS [Total Expresado en Mon. Cte.], 
	 CASE VENTA.TERMINAL_INGRESO
        WHEN 'PC-BOLETERIA01' THEN 'PC BOLETERIA 1'
        WHEN 'PC-BOLETERIA02' THEN 'PC BOLETERIA 2'
        WHEN 'PC-BOLETERIA03' THEN 'PC BOLETERIA 3'
        WHEN 'PC-BOLETERIA04' THEN 'PC BOLETERIA 4'
        WHEN 'PC-BOLETERIA05' THEN 'PC BOLETERIA 5'
        WHEN 'PC-LOCKERS' THEN 'PC LOCKERS'
        WHEN 'PUESTO01-VERDE' THEN 'PUESTO 1 VERDE'
        WHEN 'PUESTO02-AMARIL' THEN 'PUESTO 2 AMARILLO'
        WHEN 'PUESTO03-NEGRO' THEN 'PUESTO 3 NEGRO'
        WHEN 'PUESTO04-AZUL' THEN 'PUESTO 4 AZUL'
        WHEN 'PUESTO05-MARRON' THEN 'PUESTO 5 MARRON'
        WHEN 'PC-VALIDACION01' THEN 'PC VALIDACION 1'
        WHEN 'PC-VALIDACION02' THEN 'PC VALIDACION 2'
        WHEN 'PC-VALIDACION03' THEN 'PC VALIDACION 3'
        WHEN 'PC-FLOTADORES' THEN 'PC FLOTADORES'
		WHEN 'PC-ATENCION01' THEN 'PC ATENCION VISITANTES'
		WHEN 'SERVER-T' THEN 'VENTA WEB'
        ELSE VENTA.TERMINAL_INGRESO
    END AS [Puesto] 
FROM 
(SELECT DISTINCT GVA12.T_COMP, GVA12.N_COMP, GVA12.COD_CLIENT, GVA12.COD_CLASIF, GVA12.TCOMP_IN_V, GVA12.ESTADO, GVA12.IMPORTE, GVA12.UNIDADES, GVA12.FECHA_EMIS, GVA12.COTIZ, GVA12.TERMINAL_INGRESO, GVA12.COD_VENDED, CASE WHEN GVA12.ESTADO = '***' AND EXISTS (SELECT 1 FROM SBA05 WHERE SBA05.COD_COMP = GVA12.T_COMP AND SBA05.N_COMP = GVA12.N_COMP ) THEN 'Contado' WHEN (GVA12.ESTADO <> '***' AND GVA12.T_COMP <> 'REC') OR ((GVA12.ESTADO = '***' AND GVA12.T_COMP <> 'REC') AND NOT EXISTS (SELECT 1 FROM SBA05 WHERE SBA05.COD_COMP = GVA12.T_COMP AND SBA05.N_COMP = GVA12.N_COMP )) THEN 'CtaCte' END AS 'TIPO' FROM GVA12 WHERE (GVA12.ESTADO = '***'	AND EXISTS (SELECT 1 FROM SBA05 WHERE SBA05.COD_COMP = GVA12.T_COMP AND SBA05.N_COMP = GVA12.N_COMP ))	OR (GVA12.ESTADO <> '***' AND GVA12.T_COMP <> 'REC') OR ((GVA12.ESTADO = '***' AND GVA12.T_COMP <> 'REC') AND NOT EXISTS (SELECT 1 FROM SBA05 WHERE SBA05.COD_COMP = GVA12.T_COMP AND SBA05.N_COMP = GVA12.N_COMP ))) VENTA 
LEFT JOIN SBA05 ON VENTA.T_COMP = SBA05.COD_COMP AND VENTA.N_COMP = SBA05.N_COMP 
LEFT JOIN SBA01 ON (SBA01.COD_CTA = SBA05.COD_CTA) 
LEFT JOIN GVA14 ON (VENTA.COD_CLIENT = GVA14.COD_CLIENT) 
LEFT JOIN GVA16 ON 1=1 
LEFT JOIN GVA28 FAMILIA (NOLOCK) ON SUBSTRING(VENTA.COD_CLIENT,1,GVA16.LONG_FAM_C) = FAMILIA.COD_AGR 
LEFT JOIN GVA28 GRUPO (NOLOCK) ON SUBSTRING(VENTA.COD_CLIENT,0,GVA16.LONG_FAM_C + GVA16.LON_GRUP_C + 1) = GRUPO.COD_AGR 
LEFT JOIN GVA81 ON (GVA81.COD_CLASIF = VENTA.COD_CLASIF) 
LEFT JOIN GVA151 ON GVA14.COD_RUBRO = GVA151.COD_RUBRO 


WHERE 

(SBA05.RENGLON <> 0 or SBA05.RENGLON IS NULL) AND VENTA.TCOMP_IN_V IN ('FC', 'FR', 'CC', 'DC', 'RC') AND (VENTA.ESTADO <> 'ANU') AND (VENTA.COD_VENDED <> '**') AND ((SBA01.TIPO = 'T' OR SBA01.TIPO = 'C' OR (SBA01.TIPO = 'O' AND SBA01.FONDO = '1') OR (SBA01.TIPO = 'B' AND SBA01.CC_CA <> 'D')) OR SBA01.TIPO IS NULL)

GROUP BY 
	ISNULL(SBA01.COD_CTA, ' ') , SBA01.DESCRIPCIO , CASE WHEN VENTA.TIPO = 'CONTADO' AND SBA01.TIPO = 'O' THEN 'Efectivo' WHEN VENTA.TIPO = 'CONTADO' AND SBA01.TIPO = 'T' THEN 'Tarjeta' WHEN VENTA.TIPO = 'CONTADO' AND SBA01.TIPO = 'C' THEN 'Cheque de Terceros' WHEN VENTA.TIPO = 'CONTADO' AND SBA01.TIPO = 'B' THEN 'Bancos' WHEN VENTA.TIPO = 'CTACTE' THEN 'Cuenta Corriente' END , CASE WHEN VENTA.TIPO = 'CONTADO' THEN 'Venta al Contado' WHEN VENTA.TIPO = 'CTACTE' THEN 'Venta en Cuenta Corriente' END, VENTA.TERMINAL_INGRESO, VENTA.FECHA_EMIS
)