
Select 
GVA12.FECHA_EMIS AS [Fecha de Emisión],
dbo.TLMostrarComprobantecliente  (gva12.t_comp, gva12.n_comp, gva12.cod_client,case when gva12.cod_client <> '000000' then gva14.razon_soci else  gva38.RAZON_SOCI end)  AS [Comprobante] ,
--GVA12.COD_CLIENT AS [Codigo de Cliente],
--GVA14.RAZON_SOCI AS [Razon Social],
GVA12.COD_VENDED AS [Codigo de Vendedor],
GVA23.NOMBRE_VEN AS [Nombre Vendedor],
GVA12.COND_VTA AS [Condición de Venta],
GVA01.DESC_COND AS [Descripción de Cond. Venta],
SBA05.COD_CTA AS [Cuenta Fondos],
SBA01.DESCRIPCIO AS [Nombre de Cuenta Fondos],
SBA22.COD_TARJET AS [Codigo de Tarjeta],
SBA20.ID_PLAN_TARJETA AS [Cód. Promoción],
PT.DESC_PLAN_TARJETA AS [Desc. Promoción],
SBA20.CANT_CUOTA AS [Cant. Cuotas],
SBA20.COMISION [Tasa de Interes de la Tarjeta],
CUENTA.COD_CUENTA AS [Cód. cuenta] ,
CUENTA.DESC_CUENTA AS [Desc. cuenta] 
from GVA12
	Join GVA14 on GVA12.COD_CLIENT = GVA14.COD_CLIENT
	Join GVA01 on GVA01.COND_VTA = GVA12.COND_VTA
	Join SBA04 on SBA04.N_COMP = GVA12.N_COMP and SBA04.COD_COMP = GVA12.T_COMP
	Join SBA05 on SBA05.N_COMP = GVA12.N_COMP and SBA05.COD_COMP = GVA12.T_COMP
	Left Join GVA38 ON GVA38.T_COMP = GVA12.T_COMP AND GVA38.N_COMP = GVA12.N_COMP 
	JOIN GVA15 ON (GVA15.IDENT_COMP = GVA12.T_COMP)
	Join GVA23 on GVA23.COD_VENDED = Gva12.COD_VENDED
	Join SBA01 on SBA01.COD_CTA = SBA05.COD_CTA
	Join SBA22 on SBA22.ID_SBA22 = SBA01.ID_SBA22
	Join SBA20 on SBA20.COD_CTA = SBA01.COD_CTA and SBA20.T_COMP_REC = GVA12.T_COMP and SBA20.N_COMP_REC = GVA12.N_COMP
	Join PLAN_TARJETA PT on PT.ID_PLAN_TARJETA = SBA20.ID_PLAN_TARJETA
	Join ASIENTO_COMPROBANTE_GV on ASIENTO_COMPROBANTE_GV.NCOMP_IN_V = GVA12.NCOMP_IN_V 
	Join ASIENTO_GV on ASIENTO_COMPROBANTE_GV.ID_ASIENTO_COMPROBANTE_GV = ASIENTO_GV.ID_ASIENTO_COMPROBANTE_GV
	Join CUENTA on CUENTA.ID_CUENTA = ASIENTO_GV.ID_CUENTA
Group by GVA12.N_COMP, GVA12.T_COMP, GVA12.COD_VENDED, GVA12.COND_VTA , GVA12.FECHA_EMIS,
GVA12.COND_VTA, GVA01.DESC_COND, SBA05.COD_CTA, SBA22.COD_TARJET, GVA23.NOMBRE_VEN, SBA01.DESCRIPCIO,
dbo.TLMostrarComprobantecliente  (gva12.t_comp, gva12.n_comp, gva12.cod_client,case when gva12.cod_client <> '000000' then gva14.razon_soci else  gva38.RAZON_SOCI end),
SBA20.ID_PLAN_TARJETA, PT.DESC_PLAN_TARJETA, SBA20.CANT_CUOTA, SBA20.COMISION