/*Se arman dos vistas con la información del Saldo Stock y Stock Comprometido de Pruebas y Casa Santiago*/
Create View SaldoStockCasaSantiago AS (
SELECT 
	STA11.Cod_Articu AS [Cód. Artículo] ,
	Sta11.Descripcio AS [Descripción] ,
	 SUM(CASE WHEN STA11.ID_MEDIDA_CONTROL_STOCK = STA11.ID_MEDIDA_STOCK_2 THEN CANT_STOCK_2 ELSE CANT_STOCK END) AS [Saldo Stock] ,
	 SUM(CASE WHEN STA11.ID_MEDIDA_CONTROL_STOCK = STA11.ID_MEDIDA_STOCK_2 THEN CANT_COMP_2 ELSE CANT_COMP END) AS [Stock Comprometido] 
FROM 
STA11 
INNER JOIN STA19 ON STA11.COD_ARTICU = STA19.COD_ARTICU 
INNER JOIN STA22 ON STA19.COD_DEPOSI = STA22.COD_SUCURS 
LEFT JOIN (SELECT COD_ARTICU, DESCRIPCIO FROM STA11 WHERE USA_ESC = 'B') AS BASE ON (BASE.COD_ARTICU = STA11.BASE) 
LEFT JOIN MEDIDA AS MEDIDA_STOCK ON STA11.ID_MEDIDA_STOCK = MEDIDA_STOCK.ID_MEDIDA  
LEFT JOIN STA16 ON 1 = 1  
LEFT JOIN STA29 FAMILIA_ART ON SUBSTRING(STA11.COD_ARTICU, 1, STA16.LONG_FAM_A) = FAMILIA_ART.COD_AGR  
LEFT JOIN STA29 GRUPO_ART ON SUBSTRING(STA11.COD_ARTICU, 1, LONG_FAM_A + LONG_GRU_A) = GRUPO_ART.COD_AGR
WHERE 
STA11.Stock = 1
AND STA11.PERFIL <> 'N'
GROUP BY 
	STA11.Cod_Articu , Sta11.Descripcio
)

Create View SaldoStockPruebas AS (
SELECT 
	STA11.Cod_Articu AS [Cód. Artículo] ,
	Sta11.Descripcio AS [Descripción] ,
	 SUM(CASE WHEN STA11.ID_MEDIDA_CONTROL_STOCK = STA11.ID_MEDIDA_STOCK_2 THEN CANT_STOCK_2 ELSE CANT_STOCK END) AS [Saldo Stock] ,
	 SUM(CASE WHEN STA11.ID_MEDIDA_CONTROL_STOCK = STA11.ID_MEDIDA_STOCK_2 THEN CANT_COMP_2 ELSE CANT_COMP END) AS [Stock Comprometido] 
FROM 
STA11 
INNER JOIN STA19 ON STA11.COD_ARTICU = STA19.COD_ARTICU 
INNER JOIN STA22 ON STA19.COD_DEPOSI = STA22.COD_SUCURS 
LEFT JOIN (SELECT COD_ARTICU, DESCRIPCIO FROM STA11 WHERE USA_ESC = 'B') AS BASE ON (BASE.COD_ARTICU = STA11.BASE) 
LEFT JOIN MEDIDA AS MEDIDA_STOCK ON STA11.ID_MEDIDA_STOCK = MEDIDA_STOCK.ID_MEDIDA  
LEFT JOIN STA16 ON 1 = 1  
LEFT JOIN STA29 FAMILIA_ART ON SUBSTRING(STA11.COD_ARTICU, 1, STA16.LONG_FAM_A) = FAMILIA_ART.COD_AGR  
LEFT JOIN STA29 GRUPO_ART ON SUBSTRING(STA11.COD_ARTICU, 1, LONG_FAM_A + LONG_GRU_A) = GRUPO_ART.COD_AGR
WHERE 
STA11.Stock = 1
AND STA11.PERFIL <> 'N'
GROUP BY 
	STA11.Cod_Articu , Sta11.Descripcio
)


/*Luego con esas dos vistas se hace el calculo de [Saldo Stock] - [Stock Comprometido] = [Saldo Disponible]*/
SELECT 
    [Cod. Articulo],
    [Descripcion],
    SUM([Saldo Stock] - [Stock Comprometido]) AS [Saldo Disponible]
FROM (
    SELECT [Cod. Articulo], [Descripcion], [Saldo Stock], [Stock Comprometido] FROM SaldoStockPruebas
    UNION ALL
    SELECT [Cod. Articulo], [Descripcion], [Saldo Stock], [Stock Comprometido] FROM CASA_SANTIAGO_VACANZA..SaldoStockCasaSantiago
) AS CombinedResults
GROUP BY [Cod. Articulo], [Descripcion];