/*STA19: Saldos de Stock*/
--SELECT:
Select STA19.COD_ARTICU, STA11.DESCRIPCIO from STA19 
	Join STA11 on
		STA19.COD_ARTICU = STA11.COD_ARTICU
Where STA11.PERFIL = 'N' --185

--DELETE
Begin tran
DELETE FROM STA19
WHERE EXISTS (
    SELECT 1
    FROM STA11
    WHERE STA19.COD_ARTICU = STA11.COD_ARTICU
    AND STA11.PERFIL = 'N')
commit