/* STA12: Precios para costos*/

--SELECT:
Select STA12.COD_ARTICU, STA11.DESCRIPCIO from STA12 
	Join STA11 on
		STA12.COD_ARTICU = STA11.COD_ARTICU
Where STA11.PERFIL = 'N' --94

--DELETE:
Begin tran
DELETE FROM STA12
WHERE EXISTS (
    SELECT 1
    FROM STA11
    WHERE STA12.COD_ARTICU = STA11.COD_ARTICU
    AND STA11.PERFIL = 'N')
commit

