SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET DATEFORMAT DMY 
SET DATEFIRST 7 
SET DEADLOCK_PRIORITY -8;
SELECT 
	CASE WHEN GVA21.FECHA_ENTR <> '01/01/1800' THEN GVA21.FECHA_ENTR  ELSE CASE WHEN TEMP.FECHA_MINIMA <> '01/01/1800' THEN TEMP.FECHA_MINIMA ELSE NULL END END AS [Fecha Entrega] ,
	GVA21.Nro_Pedido AS [Nro. Pedido] ,
	GVA21.COD_CLIENT AS [Cód. cliente] ,
	CASE GVA21.COD_CLIENT WHEN '000000' THEN 'OCASIONAL' ELSE GVA14.RAZON_SOCI END AS [Razón social] ,
	CASE GVA21.COD_CLIENT WHEN '000000' THEN 'OCASIONAL' ELSE NOM_COM END AS [Nombre comercial] ,
	GVA21.FECHA_PEDI AS [Fecha Pedido] ,
	sum(CASE WHEN ISNULL(GVA10.INCLUY_IVA,1) = 0 AND ISNULL(GVA10.INCLUY_IMP,0) = 0 THEN 0.00 ELSE (  case when gva21.ES_PEDIDO_WEB = 1 and gva21.tienda <> 'e-Commerce' then   ((PEDIDO.Precio * (1 - PEDIDO.Descuento / 100) * PEDIDO.Cant_Pen_F) *  	CASE WHEN Gva10.Mon_Cte <> 1 THEN GVA21.Cotiz	ELSE 1 END * ( 1 - ((gva21.porc_desc +  (gva21.porcen_desc_tienda/ (CASE Temp2.Total_Sin_Descuento WHEN 0 THEN 1 ELSE Temp2.Total_Sin_Descuento END)))/100) ))  else  ((PEDIDO.Precio * (1 - PEDIDO.Descuento / 100) * PEDIDO.Cant_Pen_F) *  	CASE WHEN Gva10.Mon_Cte <> 1 THEN GVA21.Cotiz	ELSE 1 END * ( 1 - gva21.porc_desc/100 )) end ) END)  AS [Total Pendiente con impuestos] ,
	CASE GVA21.ESTADO 
		WHEN 1 THEN 'INGRESADO' 
		WHEN 2 THEN 'PENDIENTE / PARCIAL' 
		WHEN 3 THEN 'CUMPLIDO' 
		WHEN 4 THEN 'CERRADO' 
		WHEN 5 THEN 'ANULADO' 
		WHEN 6 THEN 'REVISADO'	
		WHEN 7 THEN 'DESAPROBADO' 
			ELSE '' END AS [Estado] 
FROM 
 GVA21  
INNER JOIN (SELECT GVA03.*, STA11.ID_MEDIDA_STOCK AS MEDIDA_STOCK, STA11.ID_MEDIDA_CONTROL_STOCK,  (CASE WHEN STA11.ID_MEDIDA_CONTROL_STOCK = STA11.ID_MEDIDA_STOCK_2 AND GVA03.CANT_PEN_F_2 > 0  THEN GVA03.CANT_PEN_F_2 WHEN STA11.ID_MEDIDA_CONTROL_STOCK = STA11.ID_MEDIDA_STOCK AND GVA03.CANT_PEN_F > 0  THEN GVA03.CANT_PEN_F END) AS CANTIDAD_PENDIENTE_FACTURAR FROM STA11, GVA03	WHERE GVA03.COD_ARTICU = STA11.COD_ARTICU)	AS PEDIDO  ON 	PEDIDO.Nro_Pedido = GVA21.Nro_Pedido AND PEDIDO.Talon_Ped = GVA21.Talon_Ped  
INNER JOIN 	GVA10 ON GVA21.N_Lista = GVA10.Nro_de_Lis  
LEFT JOIN (SELECT TALON_PED, NRO_PEDIDO, MIN(FEC_ENTREG) AS FECHA_MINIMA FROM GVA126  GROUP BY TALON_PED, NRO_PEDIDO ) AS TEMP ON GVA21.TALON_PED = TEMP.TALON_PED  AND GVA21.NRO_PEDIDO = TEMP.NRO_PEDIDO  
LEFT JOIN (SELECT GVA21.TALON_PED, GVA21.NRO_PEDIDO,             SUM (((CASE GVA10.MON_CTE WHEN 1 THEN GVA03.PRECIO ELSE (GVA03.PRECIO * GVA21.Cotiz) END ) *                   (1 - (GVA03.DESCUENTO) / 100)) * (GVA03.Cant_Pen_F)) TOTAL_SIN_DESCUENTO             FROM GVA21             
INNER JOIN GVA10	ON GVA21.N_Lista = GVA10.Nro_de_Lis             INNER  JOIN	GVA03 ON (GVA21.TALON_PED = GVA03.TALON_PED AND  GVA21.NRO_PEDIDO = GVA03.NRO_PEDIDO)             GROUP BY GVA21.TALON_PED, GVA21.NRO_PEDIDO) AS TEMP2             ON GVA21.TALON_PED = TEMP2.TALON_PED AND GVA21.NRO_PEDIDO = TEMP2.NRO_PEDIDO  
LEFT JOIN (SELECT DISTINCT COND_VTA, DESC_COND FROM GVA01) AS COND  ON COND.COND_VTA = GVA21.COND_VTA  
INNER JOIN 	GVA23 ON GVA21.COD_VENDED = GVA23.COD_VENDED  
LEFT JOIN GVA81 ON GVA81.COD_CLASIF = GVA21.COD_CLASIF 
INNER JOIN 	GVA24	ON GVA21.COD_TRANSP = GVA24.COD_TRANSP  
LEFT JOIN 	GVA14	ON GVA21.COD_CLIENT = GVA14.COD_CLIENT  
LEFT JOIN 	GVA05	ON GVA14.COD_ZONA = GVA05.COD_ZONA  
LEFT JOIN	GVA18	ON GVA14.COD_PROVIN = GVA18.COD_PROVIN  
LEFT JOIN GVA133 ON GVA18.COD_PAIS = GVA133.COD_PAIS  
INNER JOIN	GVA43 ON GVA43.TALONARIO = GVA21.TALON_PED  
INNER JOIN	STA22 ON GVA21.COD_SUCURS = STA22.COD_SUCURS  
LEFT JOIN DIRECCION_ENTREGA ON GVA21.ID_DIRECCION_ENTREGA = DIRECCION_ENTREGA.ID_DIRECCION_ENTREGA 
LEFT JOIN (SELECT gva03.nro_pedido, gva03.talon_ped                   FROM gva03                    
LEFT JOIN STA11 ON STA11.COD_ARTICU = GVA03.COD_ARTICU              WHERE (((Sta11.ID_MEDIDA_STOCK = STA11.ID_MEDIDA_CONTROL_STOCK) and (gva03.cant_pen_f > 0)) OR ((Sta11.ID_MEDIDA_STOCK <> STA11.ID_MEDIDA_CONTROL_STOCK) and(gva03.cant_pen_f_2 > 0)))                AND (((Sta11.ID_MEDIDA_STOCK = STA11.ID_MEDIDA_CONTROL_STOCK) and (gva03.cant_pen_d <> gva03.cant_pedid)) OR ((Sta11.ID_MEDIDA_STOCK <> STA11.ID_MEDIDA_CONTROL_STOCK) and (gva03.cant_pen_d_2 <> gva03.cant_pedid_2)))                  AND (((Sta11.ID_MEDIDA_STOCK = STA11.ID_MEDIDA_CONTROL_STOCK) and (gva03.cant_pen_f > gva03.cant_pen_d)) OR ((Sta11.ID_MEDIDA_STOCK <> STA11.ID_MEDIDA_CONTROL_STOCK) and (gva03.cant_pen_f_2 > gva03.cant_pen_d_2)))                GROUP BY GVA03.NRO_PEDIDO, GVA03.TALON_PED) AS REMITIDO     ON REMITIDO.TALON_PED = GVA21.TALON_PED AND REMITIDO.NRO_PEDIDO = GVA21.NRO_PEDIDO		
LEFT JOIN (SELECT gva03.NRO_PEDIDO, GVA03.TALON_PED,                     SUM(CASE WHEN STA11.ID_MEDIDA_CONTROL_STOCK = STA11.ID_MEDIDA_STOCK_2 AND GVA03.CANT_PEN_F_2 > 0  THEN GVA03.CANT_PEN_F_2                              WHEN STA11.ID_MEDIDA_CONTROL_STOCK = STA11.ID_MEDIDA_STOCK   AND GVA03.CANT_PEN_F   > 0  THEN GVA03.CANT_PEN_F   END) AS CANTIDAD_PENDIENTE_FACTURAR                   FROM GVA03                   
INNER JOIN STA11 ON GVA03.COD_ARTICU = STA11.COD_ARTICU                GROUP BY GVA03.NRO_PEDIDO, GVA03.TALON_PED)               AS PEDIDO_PENDIENTE ON PEDIDO_PENDIENTE.NRO_PEDIDO = GVA21.NRO_PEDIDO AND PEDIDO_PENDIENTE.TALON_PED = GVA21.TALON_PED 
LEFT JOIN ACTIVIDAD_EMPRESA_AFIP ON GVA21.ID_ACTIVIDAD_EMPRESA_AFIP = ACTIVIDAD_EMPRESA_AFIP.ID_ACTIVIDAD_EMPRESA_AFIP  
LEFT JOIN TIPO_DOCUMENTO_GV ON TIPO_DOCUMENTO_GV.COD_TIPO_DOCUMENTO_GV = GVA21.TIPO_DOCUMENTO_PAGADOR  
LEFT JOIN EMPRESA ON 1 = 1  
LEFT JOIN SUCURSAL ON ((ISNULL(GVA21.NRO_SUCURS, 0) = 0 AND SUCURSAL.ID_SUCURSAL = EMPRESA.ID_SUCURSAL) OR GVA21.NRO_SUCURS = SUCURSAL.NRO_SUCURSAL)  
LEFT JOIN GVA38 ON gva21.NRO_PEDIDO=gva38.N_COMP and gva38.T_COMP='PED'  
LEFT JOIN	GVA18 PROV_OCASIONAL	ON PROV_OCASIONAL.COD_PROVIN = GVA38.COD_PROVIN 


WHERE 

((IsNull(PEDIDO.COD_ARTICU_KIT,'')= '') or (PEDIDO.COD_ARTICU <> '' and PEDIDO.PROMOCION=1)) and EXISTS ( SELECT TOP 1 GVA03.NRO_PEDIDO FROM GVA03 WHERE GVA03.Talon_Ped = GVA21.Talon_Ped AND GVA03.Nro_Pedido = GVA21.Nro_Pedido AND PEDIDO_PENDIENTE.CANTIDAD_PENDIENTE_FACTURAR > 0) AND (PEDIDO.COD_ARTICU_KIT = '' OR (PEDIDO.COD_ARTICU_KIT <> '' AND PEDIDO.RENGL_PADR = 0)) AND (GVA21.EXPORTADO = 0 OR GVA21.METODO_EXPORTACION = 'FACTURA_ORIGEN_REMITO_DESTINO')

GROUP BY 
	GVA21.Talon_Ped , GVA21.Nro_Pedido , GVA21.COD_CLIENT , CASE GVA21.COD_CLIENT WHEN '000000' THEN 'OCASIONAL' ELSE GVA14.RAZON_SOCI END , CASE GVA21.COD_CLIENT WHEN '000000' THEN 'OCASIONAL' ELSE NOM_COM END , GVA21.FECHA_PEDI ,  CASE WHEN GVA21.FECHA_ENTR <> '01/01/1800' THEN GVA21.FECHA_ENTR  ELSE CASE WHEN TEMP.FECHA_MINIMA <> '01/01/1800' THEN TEMP.FECHA_MINIMA ELSE NULL END END , CASE GVA21.ESTADO WHEN 1 THEN 'INGRESADO' WHEN 2 THEN 'PENDIENTE / PARCIAL' WHEN 3 THEN 'CUMPLIDO' WHEN 4 THEN 'CERRADO' WHEN 5 THEN 'ANULADO' WHEN 6 THEN 'REVISADO'	WHEN 7 THEN 'DESAPROBADO' ELSE '' END
