
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET DATEFORMAT DMY
SET DATEFIRST 7
SET DEADLOCK_PRIORITY -8;


SELECT --GVA08.TALONARIO AS [Talonario] ,
 CASE T_CLIENTE
     WHEN 'H' THEN GVA14.NOM_COM
     WHEN 'P' THEN GVA19.NOM_COM
     WHEN 'O' THEN GVA38.RAZON_SOCI
 END AS [Nombre Comercial/Razon Social],
 GVA08.OBSERVA_1 AS [Titulo],
 GVA08.FECHA_ALTA AS [Fecha],
 GVA08.N_COTIZ AS [Nro. Cotización],
 CASE GVA08.MON_CTE
     WHEN 1 THEN 'CORRIENTE'
     WHEN 0 THEN 'EXTRANJERA'
 END AS [Moneda],
 GVA08.COD_CLIENT AS [Cód. cliente] , --GVA08.COD_VENDED AS [Cód. vendedor] ,
 --GVA23.NOMBRE_VEN AS [Vendedor] ,
 GVA08.FECHA_VIG AS [Fecha de vigencia] , --	CASE GVA08.ESTADO WHEN 1 THEN 'INGRESADA' WHEN 2 THEN 'AUTORIZADA' WHEN 3 THEN 'ACEPTADA'  WHEN 4 THEN 'GENERADA PEDIDO' WHEN 5 THEN 'ANULADA' ELSE '' END AS [Estado de la Cotizacion] ,
 CASE
     WHEN GVA08.PERDIDA = 1 THEN 'AUTORIZADA (PERDIDA)'
     ELSE CASE GVA08.ESTADO
              WHEN 1 THEN 'INGRESADA'
              WHEN 2 THEN 'AUTORIZADA'
              WHEN 3 THEN 'ACEPTADA'
              WHEN 4 THEN 'PEDIDA'
              WHEN 5 THEN 'ANULADA'
              ELSE ''
          END
 END AS [Estado de la Cotizacion],
 GVA21.NRO_PEDIDO AS [Numero de Pedido],
 CASE GVA21.ESTADO
     WHEN 1 THEN 'INGRESADO'
     WHEN 2 THEN 'PENDIENTE'
     WHEN 3 THEN 'FACTURADO'
     WHEN 4 THEN 'CERRADO'
     WHEN 5 THEN 'ANULADO'
     WHEN 6 THEN 'REVISADO'
     WHEN 7 THEN 'DESAPROBADO'
     ELSE ''
 END AS [Estado del Pedido],
 GVA55.N_COMP AS [Comprobante de Venta relacionado] --CASE T_CLIENTE WHEN 'H' THEN 'HABITUAL' WHEN 'O' THEN 'OCASIONAL' WHEN 'P' THEN 'POTENCIAL' END AS [Tipo de Cliente],
 --DIRECCION_ENTREGA.COD_DIRECCION_ENTREGA AS [Cód. Dirección de entrega]
FROM GVA08
LEFT JOIN GVA14 ON GVA14.COD_CLIENT = GVA08.COD_CLIENT
LEFT JOIN GVA19 ON GVA19.COD_CLIENT = GVA08.COD_CLIENT
LEFT JOIN GVA38 ON GVA38.T_COMP = 'COT'
AND GVA38.N_COMP = GVA08.N_COTIZ
LEFT JOIN GVA37 ON GVA37.N_COTIZ = GVA08.N_COTIZ
LEFT JOIN GVA21 ON GVA21.NRO_PEDIDO = GVA37.NRO_PEDIDO
LEFT JOIN GVA55 ON GVA55.NRO_PEDIDO = GVA21.NRO_PEDIDO
LEFT JOIN GVA65 ON GVA65.COD_PERDID = GVA08.COD_PERDID --INNER JOIN GVA23 ON GVA08.COD_VENDED = GVA23.COD_VENDED
--LEFT JOIN DIRECCION_ENTREGA ON DIRECCION_ENTREGA.ID_DIRECCION_ENTREGA = GVA08.ID_DIRECCION_ENTREGA
GROUP BY GVA08.TALONARIO,
         GVA08.N_COTIZ,
         GVA08.OBSERVA_1,
         GVA08.FECHA_ALTA,
         GVA08.COD_CLIENT,
         CASE T_CLIENTE
             WHEN 'H' THEN GVA14.NOM_COM
             WHEN 'P' THEN GVA19.NOM_COM
             WHEN 'O' THEN GVA38.RAZON_SOCI
         END,
         GVA08.COD_VENDED,
         GVA08.FECHA_VIG,
         CASE GVA08.ESTADO
             WHEN 1 THEN 'INGRESADA'
             WHEN 2 THEN 'AUTORIZADA'
             WHEN 3 THEN 'ACEPTADA'
             WHEN 4 THEN 'GENERADA PEDIDO'
             WHEN 5 THEN 'ANULADA'
             ELSE ''
         END,
         CASE GVA08.MON_CTE
             WHEN 1 THEN 'CORRIENTE'
             WHEN 0 THEN 'EXTRANJERA'
         END,
         CASE T_CLIENTE
             WHEN 'H' THEN 'HABITUAL'
             WHEN 'O' THEN 'OCASIONAL'
             WHEN 'P' THEN 'POTENCIAL'
         END,
         CASE GVA08.PERDIDA
             WHEN 0 THEN 'NO'
             ELSE 'SI'
         END,
         GVA21.NRO_PEDIDO,
         CASE GVA21.ESTADO
             WHEN 1 THEN 'INGRESADO'
             WHEN 2 THEN 'PENDIENTE'
             WHEN 3 THEN 'FACTURADO'
             WHEN 4 THEN 'CERRADO'
             WHEN 5 THEN 'ANULADO'
             WHEN 6 THEN 'REVISADO'
             WHEN 7 THEN 'DESAPROBADO'
             ELSE ''
         END,
         GVA55.N_COMP,
         GVA08.PERDIDA,
         GVA08.ESTADO