SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET DATEFORMAT DMY 
SET DATEFIRST 7 
SET DEADLOCK_PRIORITY -8;

SELECT 
 SUCURSAL.NRO_SUCURSAL AS [NRO. SUCURSAL] ,
 CTA02.T_COMP AS [TIPO COMPROBANTE] ,
 CTA02.N_COMP AS [NRO. COMPROBANTE] ,
 CTA02.FECHA_EMIS AS [FECHA DE EMISIÛN] 
FROM 
 CTA02 
LEFT JOIN (
 SELECT 
 CTA02.NRO_SUCURS, 
 CTA02.T_COMP, 
 CTA02.N_COMP, 
 SUM(CASE WHEN CTA_TIPO_COMPROBANTE_VENTAS.TIPO_COMP = 'C' THEN CTA29.MONTO * (-1) ELSE CTA29.MONTO END) TOTAL 
 FROM CTA02 
 INNER JOIN CTA_TIPO_COMPROBANTE_VENTAS ON CTA02.T_COMP = CTA_TIPO_COMPROBANTE_VENTAS.IDENT_COMP AND CTA02.NRO_SUCURS = CTA_TIPO_COMPROBANTE_VENTAS.NRO_SUCURS 
 LEFT JOIN CTA28 ON CTA02.N_COMP = CTA28.N_COMP AND CTA02.T_COMP = CTA28.COD_COMP 
 LEFT JOIN CTA29 ON CTA28.N_COMP = CTA29.N_COMP AND CTA28.COD_COMP = CTA29.COD_COMP AND CTA28.BARRA = CTA29.BARRA 
 JOIN CTA_CUENTA_TESORERIA ON CTA29.COD_CTA = CTA_CUENTA_TESORERIA.COD_CTA_CUENTA_TESORERIA 
 WHERE 
 CTA02.COD_VENDED <> '**' AND 
 CTA02.ESTADO <> 'ANU' AND	
 CTA02.T_COMP <> 'REC' AND 
 CTA_TIPO_COMPROBANTE_VENTAS.VENT_ART = 'S' AND 
 CTA_CUENTA_TESORERIA.FONDO = 1 
 GROUP BY CTA02.NRO_SUCURS, CTA02.T_COMP, CTA02.N_COMP
) CONTADO ON CTA02.NRO_SUCURS = CONTADO.NRO_SUCURS AND CTA02.T_COMP = CONTADO.T_COMP AND CTA02.N_COMP = CONTADO.N_COMP 
INNER JOIN SUCURSAL(NOLOCK) ON CTA02.NRO_SUCURS = SUCURSAL.NRO_SUCURSAL 
LEFT JOIN CTA_CLIENTE(NOLOCK) ON CTA02.COD_CLIENT = CTA_CLIENTE.COD_CLIENTE 
LEFT JOIN CTA_TIPO_COMPROBANTE_VENTAS(NOLOCK) ON CTA02.T_COMP = CTA_TIPO_COMPROBANTE_VENTAS.IDENT_COMP AND CTA02.NRO_SUCURS = CTA_TIPO_COMPROBANTE_VENTAS.NRO_SUCURS 
LEFT JOIN CTA_VENDEDOR(NOLOCK) ON CTA02.COD_VENDED = CTA_VENDEDOR.COD_VENDEDOR
WHERE 
 CTA02.COD_VENDED <> '**' AND 
 CTA02.ESTADO <> 'ANU' AND 
 CTA02.T_COMP <> 'REC' AND 
 CTA_TIPO_COMPROBANTE_VENTAS.VENT_ART = 'S' AND 
 (CTA02.ESTADO <> '***' OR ISNULL(CONTADO.N_COMP,'') <> '') 
 AND 
 SUCURSAL.NRO_SUCURSAL = '1' 
 AND 
 LEFT(CTA02.N_COMP, 6) IN ('T00025', 'A00025', 'B00025')
GROUP BY 
 SUCURSAL.NRO_SUCURSAL, CTA02.T_COMP, CTA02.N_COMP, CTA02.FECHA_EMIS