SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET DATEFORMAT DMY 
SET DATEFIRST 7 
SET DEADLOCK_PRIORITY -8;
SELECT 
	CTA02.NRO_SUCURS AS [Nro. Sucursal] ,
	CTA02.FECHA_EMIS AS [Fecha] ,
	CTA02.T_COMP AS [Tipo de comprobante] ,
	CTA02.N_COMP AS [Nro. Comprobante] ,
	--SUM(dbo.SUMGVA12IMPORTES ('BIMONCTE', CTA02.COTIZ, 1, CASE SUM_CTA_CLIENTE.CLAUSULA WHEN 1 THEN 'S' ELSE 'N' END, 'S', CTA_TIPO_COMPROBANTE_VENTAS.TIPO_COMP, CASE CTA02.MON_CTE WHEN 1 THEN 'S' ELSE 'N' END, 0, 0, 2, CTA02.IMPORTE_BO)) AS [Total bonificado] ,
	--SUM(dbo.SUMGVA12IMPORTES ('BIMONCTE', CTA02.COTIZ, 1, CASE SUM_CTA_CLIENTE.CLAUSULA WHEN 1 THEN 'S' ELSE 'N' END, 'N', CTA_TIPO_COMPROBANTE_VENTAS.TIPO_COMP, CASE CTA02.MON_CTE WHEN 1 THEN 'S' ELSE 'N' END, CTA02.IMPORTE_IV, IMPUESTOS.IMPORTE, 2, CTA02.IMPORTE) ) AS [Total sin impuestos] ,
	SUM(dbo.SUMGVA12IMPORTES ('BIMONCTE', CTA02.COTIZ, 1, CASE SUM_CTA_CLIENTE.CLAUSULA WHEN 1 THEN 'S' ELSE 'N' END, 'S', CTA_TIPO_COMPROBANTE_VENTAS.TIPO_COMP, CASE CTA02.MON_CTE WHEN 1 THEN 'S' ELSE 'N' END, CTA02.IMPORTE_IV, IMPUESTOS.IMPORTE, 2, CTA02.IMPORTE) ) AS [Total] 
FROM 
CTA02 (NOLOCK) JOIN CTA_TIPO_COMPROBANTE_VENTAS ON CTA02.T_COMP = CTA_TIPO_COMPROBANTE_VENTAS.IDENT_COMP AND CTA02.NRO_SUCURS = CTA_TIPO_COMPROBANTE_VENTAS.NRO_SUCURS 
LEFT JOIN (SELECT T_COMP, N_COMP, SUM(CTA04.IMPORTE) AS IMPORTE FROM CTA04 WHERE T_COMP <> 'REC' AND (COD_ALICUO BETWEEN 21 AND 82 OR COD_IMPUES <> '') GROUP BY T_COMP, N_COMP ) IMPUESTOS ON(CTA02.T_COMP = IMPUESTOS.T_COMP AND CTA02.N_COMP = IMPUESTOS.N_COMP) 
LEFT JOIN CTA_CLIENTE SUM_CTA_CLIENTE ON (CTA02.COD_CLIENT = SUM_CTA_CLIENTE.COD_CLIENTE) 


WHERE 

CTA02.T_COMP <> 'REC' AND CTA02.COD_VENDED <> '**'
 AND LEFT(CTA02.N_COMP, 6) IN ('T00025', 'A00025', 'B00025')

GROUP BY 
	CTA02.NRO_SUCURS , CTA02.T_COMP , CTA02.N_COMP , CTA02.FECHA_EMIS