SELECT
	'TIN' AS [TIPO COMPROBANTE],
	' 0000000000043' AS [NUMERO COMPROBANTE],
    STA19.COD_ARTICU AS [CÓDIGO],
    STA11.DESCRIPCIO AS [DESCRIPCIÓN],
    STA19.COD_DEPOSI AS [DEPÓSITO],
	'' AS [NÚMERO PARTIDA],
	'NO' [TIENE STOCK],
    MEDIDA.DESC_MEDIDA AS [UNIDAD MEDIDA],
	CAST(STA19.CANT_STOCK AS INT) AS [CANTIDAD REAL],
    CAST(ABS(STA19.CANT_STOCK) AS INT) AS [CANTIDAD SISTEMA],
	'' AS [DIFERENCIA],
	'' AS [UNIDAD MEDIDA 2],
	'' AS [CANTIDAD REAL 2],
	'' AS [CANTIDAD SISTEMA 2],
	'' AS [CANTIDAD SISTEMA 2],
	'' AS [ELIMINAR ARTICULO]
FROM
    STA19
		JOIN STA11 
			ON STA19.COD_ARTICU = STA11.COD_ARTICU
		JOIN MEDIDA 
			ON STA11.ID_MEDIDA_CONTROL_STOCK = MEDIDA.ID_MEDIDA
WHERE
    STA19.CANT_STOCK != '0.0000000'
		AND STA19.CANT_STOCK NOT LIKE '-%'
		AND COD_DEPOSI = '02'
		AND STA11.PERFIL != 'N'