/*Esta vista lo que hace es traer la Bonificación entre Cliente-Articulo*/
CREATE VIEW BONIFICACION_ARTICULO_CLIENTE AS  
SELECT GVA11.COD_CLIENT AS [CODIGO_CLIENTE]  
,RAZON_SOCI AS [RAZON_SOCIAL]  
,GVA11.COD_ARTICU AS [CODIGO_ARTICULO],  
DESCRIPCIO AS [DESCRIPCION_ARTICULO],  
GVA11.BONIF AS [BONIFICACION],
CASE
        WHEN AVG(GVA11.BONIF) >= 0 AND AVG(GVA11.BONIF) < 10 THEN '0-9'
		WHEN AVG(GVA11.BONIF) >= 10 AND AVG(GVA11.BONIF) < 20 THEN '10-19'
		WHEN AVG(GVA11.BONIF) >= 20 AND AVG(GVA11.BONIF) < 100 THEN '20-99'
        ELSE 'Otros'
END AS [RANGO_BONIFICACION]
FROM GVA11  
JOIN STA11 ON STA11.COD_ARTICU=GVA11.COD_ARTICU  
JOIN GVA14 ON GVA14.COD_CLIENT=GVA11.COD_CLIENT
Group by BONIF, GVA11.COD_CLIENT, GVA14.RAZON_SOCI, GVA11.COD_ARTICU, STA11.DESCRIPCIO