CREATE PROCEDURE ActualizarPrecios
AS
BEGIN
WITH PreciosActualizados AS (
    SELECT
        GVA17.COD_ARTICU,
        GVA21.N_LISTA,
        MAX(GVA17.FECHA_MODI) AS FECHA_ACTUALIZACION, -- Obtenemos la fecha de actualización más reciente
        GVA17.PRECIO AS PRECIO_ACTUALIZADO
    FROM GVA17
    INNER JOIN GVA10 ON GVA17.NRO_DE_LIS = GVA10.NRO_DE_LIS
    INNER JOIN NEXO_PEDIDOS_ORDEN NPO ON GVA10.NRO_DE_LIS = NPO.LISTA_PRECIO
    INNER JOIN GVA21 ON NPO.ID_NEXO_PEDIDOS_ORDEN = GVA21.ID_NEXO_PEDIDOS_ORDEN
    WHERE GVA21.ES_PEDIDO_WEB = '1'
      AND NPO.ESTADO_ORDEN = 'En Proceso'
    GROUP BY GVA17.COD_ARTICU, GVA21.N_LISTA, GVA17.PRECIO
)
UPDATE GVA03
SET GVA03.PRECIO = PA.PRECIO_ACTUALIZADO
FROM GVA03
INNER JOIN GVA21 ON GVA03.NRO_PEDIDO = GVA21.NRO_PEDIDO
INNER JOIN NEXO_PEDIDOS_ORDEN NPO ON NPO.ID_NEXO_PEDIDOS_ORDEN = GVA21.ID_NEXO_PEDIDOS_ORDEN
INNER JOIN PreciosActualizados PA ON GVA03.COD_ARTICU = PA.COD_ARTICU AND GVA21.N_LISTA = PA.N_LISTA
WHERE GVA21.ES_PEDIDO_WEB = '1'
  AND NPO.ESTADO_ORDEN = 'En Proceso'
 END