/*Clientes nuevos del Mes c/ su facturación mensual*/
SELECT
    GVA12.COD_CLIENT AS [Código de Cliente],
    GVA14.RAZON_SOCI AS [Razón Social],
    COUNT(CASE WHEN GVA12.T_COMP = 'FAC' THEN GVA12.N_COMP END) AS [Cantidad de Compras],
    SUM(CASE WHEN GVA12.T_COMP = 'FAC' THEN GVA12.IMPORTE ELSE 0 END) +
    SUM(CASE WHEN GVA12.T_COMP = 'N/C' THEN -GVA12.IMPORTE ELSE 0 END) AS [Facturación Total]
FROM
    GVA12
JOIN
    GVA15 ON GVA12.T_COMP = GVA15.IDENT_COMP
JOIN
    GVA14 ON GVA12.COD_CLIENT = GVA14.COD_CLIENT
WHERE
    GVA12.COD_CLIENT NOT IN (
        SELECT COD_CLIENT
        FROM GVA12
        WHERE
            MONTH(FECHA_EMIS) < MONTH(GETDATE())
            OR (MONTH(FECHA_EMIS) = MONTH(GETDATE()) AND YEAR(FECHA_EMIS) < YEAR(GETDATE()))
    )
    AND MONTH(GVA12.FECHA_EMIS) = MONTH(GETDATE())
    AND YEAR(GVA12.FECHA_EMIS) = YEAR(GETDATE())
	AND GVA12.COD_VENDED IN (04,05,06,07)
GROUP BY
    GVA12.COD_CLIENT,
    GVA14.RAZON_SOCI;
