SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET DATEFORMAT DMY 
SET DATEFIRST 7 
SET DEADLOCK_PRIORITY -8;
Select * from VentasXProveedorMensual

--Se crea la query para que traiga sumarizadas las ventas por proveedor y poder revisar que proveedor es quien más se vende.
Create View VentasXProveedorMensual AS (
SELECT 
	SUM( CASE WHEN CTA02.TCOMP_IN_V = 'CC' then (-1) ELSE (1) END *  CASE 'BIMONCTE' WHEN 'BIMONCTE' THEN   (CASE CTA02.MON_CTE WHEN 1 THEN CASE 'NO' WHEN 'NO'                                   THEN (CTA03.PRECIO_NET * CTA03.CANTIDAD)                                    ELSE CASE CTA02.IMPORTE WHEN 0 THEN (CTA03.PRECIO_NET * CTA03.CANTIDAD)                                        ELSE ((CTA03.PRECIO_NET * CTA03.CANTIDAD) - ((CTA03.PRECIO_NET * CTA03.CANTIDAD) * CTA02.PORC_BONIF/100) +                                        ((CTA03.PRECIO_NET * CTA03.CANTIDAD) * (CTA02.IMPORTE_FL/(CTA02.IMPORTE-CTA02.IMPORTE_FL+CTA02.IMPORTE_BO-CTA02.IMPORTE_IV-CTA02.IMPORTE_IN-ISNULL(IMPUESTOS.IMPORTE,0)))) + ((CTA03.PRECIO_NET * CTA03.CANTIDAD)                                        * CTA02.PORC_RECARGO/100))  END END                                  ELSE CASE 'NO' WHEN 'NO'                                   THEN (CTA03.PRECIO_NET * CTA03.CANTIDAD) * CTA02.COTIZ                                     ELSE CASE CTA02.IMPORTE WHEN 0 THEN (CTA03.PRECIO_NET * CTA03.CANTIDAD) * CTA02.COTIZ                                        ELSE ((CTA03.PRECIO_NET * CTA03.CANTIDAD) - ((CTA03.PRECIO_NET * CTA03.CANTIDAD) * CTA02.PORC_BONIF/100) +                                        ((CTA03.PRECIO_NET * CTA03.CANTIDAD) * (CTA02.IMPORTE_FL/(CTA02.IMPORTE-CTA02.IMPORTE_FL+CTA02.IMPORTE_BO-CTA02.IMPORTE_IV-CTA02.IMPORTE_IN-ISNULL(IMPUESTOS.IMPORTE,0)))) + ((CTA03.PRECIO_NET * CTA03.CANTIDAD)                                        * CTA02.PORC_RECARGO/100))  * CTA02.COTIZ END END                             END)  WHEN 'BIORIGEN' THEN   (CASE CTA02.MON_CTE WHEN 1 THEN CASE CTA02.COTIZ WHEN 0                                   THEN 0                                   ELSE CASE 'NO' WHEN 'NO'                                        THEN (CTA03.PRECIO_NET * CTA03.CANTIDAD)   / CTA02.COTIZ                                         ELSE CASE CTA02.IMPORTE WHEN 0 THEN (CTA03.PRECIO_NET * CTA03.CANTIDAD)/ CTA02.COTIZ                                              ELSE ((CTA03.PRECIO_NET * CTA03.CANTIDAD) - ((CTA03.PRECIO_NET * CTA03.CANTIDAD) * CTA02.PORC_BONIF/100) +                                                           ((CTA03.PRECIO_NET * CTA03.CANTIDAD) * (CTA02.IMPORTE_FL/(CTA02.IMPORTE-CTA02.IMPORTE_FL+CTA02.IMPORTE_BO-CTA02.IMPORTE_IV-CTA02.IMPORTE_IN-ISNULL(IMPUESTOS.IMPORTE,0))))                                                           + ((CTA03.PRECIO_NET * CTA03.CANTIDAD) * CTA02.PORC_RECARGO/100))  / CTA02.COTIZ END END                                        END                                   ELSE CASE 'NO' WHEN 'NO'                                   THEN (CTA03.PRECIO_NET * CTA03.CANTIDAD)                                    ELSE CASE CTA02.IMPORTE WHEN 0 THEN (CTA03.PRECIO_NET * CTA03.CANTIDAD)                                        ELSE ((CTA03.PRECIO_NET * CTA03.CANTIDAD) - ((CTA03.PRECIO_NET * CTA03.CANTIDAD) * CTA02.PORC_BONIF/100) +                                                           ((CTA03.PRECIO_NET * CTA03.CANTIDAD) * (CTA02.IMPORTE_FL/(CTA02.IMPORTE-CTA02.IMPORTE_FL+CTA02.IMPORTE_BO-CTA02.IMPORTE_IV-CTA02.IMPORTE_IN-ISNULL(IMPUESTOS.IMPORTE,0)))) +                                                           ((CTA03.PRECIO_NET * CTA03.CANTIDAD) * CTA02.PORC_RECARGO/100))  END END                              END)  WHEN 'BICOTIZ'  THEN CASE 1  WHEN 0 THEN 0  ELSE   (CASE CTA02.MON_CTE WHEN 1 THEN CASE 'NO' WHEN 'NO'                                THEN (CTA03.PRECIO_NET * CTA03.CANTIDAD)  / 1                                ELSE CASE CTA02.IMPORTE WHEN 0 THEN (CTA03.PRECIO_NET * CTA03.CANTIDAD)  / 1                                      ELSE ((CTA03.PRECIO_NET * CTA03.CANTIDAD) - ((CTA03.PRECIO_NET * CTA03.CANTIDAD) * CTA02.PORC_BONIF/100) +                                     ((CTA03.PRECIO_NET * CTA03.CANTIDAD) * (CTA02.IMPORTE_FL/(CTA02.IMPORTE-CTA02.IMPORTE_FL+CTA02.IMPORTE_BO-CTA02.IMPORTE_IV-CTA02.IMPORTE_IN-ISNULL(IMPUESTOS.IMPORTE,0)))) +                                     ((CTA03.PRECIO_NET * CTA03.CANTIDAD) * CTA02.PORC_RECARGO/100))                                                           / 1 END END                             ELSE CASE 'NO' WHEN 'NO'                              THEN (CTA03.PRECIO_NET * CTA03.CANTIDAD) * CTA02.COTIZ  / 1                                ELSE CASE CTA02.IMPORTE WHEN 0 THEN  (CTA03.PRECIO_NET * CTA03.CANTIDAD) * CTA02.COTIZ  / 1                                     ELSE ((CTA03.PRECIO_NET * CTA03.CANTIDAD) - ((CTA03.PRECIO_NET * CTA03.CANTIDAD) * CTA02.PORC_BONIF/100) +                                             ((CTA03.PRECIO_NET * CTA03.CANTIDAD) * (CTA02.IMPORTE_FL/(CTA02.IMPORTE-CTA02.IMPORTE_FL+CTA02.IMPORTE_BO-CTA02.IMPORTE_IV-CTA02.IMPORTE_IN-ISNULL(IMPUESTOS.IMPORTE,0)))) +                                              ((CTA03.PRECIO_NET * CTA03.CANTIDAD) * CTA02.PORC_RECARGO/100)) * CTA02.COTIZ  / 1   END END                              END)  END END      )  AS [Importe] ,
	CASE WHEN PROVEEDOR_HABITUAL_ART.COD_PROVEE IS NULL THEN    CPA01.NOM_PROVEE ELSE CPA01_PROV_HABITUAL.NOM_PROVEE END AS [Nombre proveedor] 
FROM 
CTA03 (NOLOCK)  
INNER JOIN CTA02 (NOLOCK) ON 
(CTA02.N_COMP = CTA03.N_COMP AND CTA02.T_COMP = CTA03.T_COMP AND CTA03.NRO_SUCURS = CTA02.NRO_SUCURS)

LEFT JOIN CPA15 AS PROVEEDOR_HABITUAL_ART ON CTA03.COD_ARTICU = PROVEEDOR_HABITUAL_ART.COD_ARTICU AND PROVEEDOR_HABITUAL_ART.PROV_HABITUAL = 'S'
 
LEFT JOIN (SELECT COD_ARTICU, MIN(CPA15.COD_PROVEE) COD_PROVEE FROM CPA15 GROUP BY COD_ARTICU) AS PROVEEDOR_ART ON 
CTA03.Cod_Articu = PROVEEDOR_ART.COD_ARTICU

LEFT JOIN CPA01 (NOLOCK) AS CPA01_PROV_HABITUAL ON PROVEEDOR_HABITUAL_ART.COD_PROVEE = CPA01_PROV_HABITUAL.COD_PROVEE 
 
LEFT JOIN CPA01 (NOLOCK) ON 
CASE WHEN PROVEEDOR_HABITUAL_ART.COD_PROVEE IS NULL THEN    ISNULL(PROVEEDOR_ART.COD_PROVEE, '' ) ELSE PROVEEDOR_HABITUAL_ART.COD_PROVEE END = CPA01.COD_PROVEE

LEFT JOIN(SELECT  NRO_SUCURS, T_COMP, N_COMP, SUM(IMPORTE) AS IMPORTE           FROM CTA04           WHERE (COD_IMPUES <>'') OR ( (COD_ALICUO BETWEEN 21 AND 80 ) OR COD_ALICUO = 82)           GROUP BY NRO_SUCURS, T_COMP, N_COMP) AS IMPUESTOS ON IMPUESTOS.T_COMP= CTA02.T_COMP AND IMPUESTOS.N_COMP = CTA02.N_COMP AND IMPUESTOS.NRO_SUCURS= CTA02.NRO_SUCURS 
 
LEFT JOIN CTA_ARTICULO (NOLOCK) CTA_ARTICULO2 ON CTA03.COD_ARTICU = CTA_ARTICULO2.COD_ARTICULO  
LEFT JOIN SUCURSAL (NOLOCK) SUCURSAL2 ON CTA03.NRO_SUCURS = SUCURSAL2.NRO_SUCURSAL  
LEFT JOIN CTA_DEPOSITO (NOLOCK) CTA_DEPOSITO2 ON CTA03.COD_DEPOSI = CTA_DEPOSITO2.COD_CTA_DEPOSITO  
LEFT JOIN  V_TN_SALDOS_STOCK_CENTRAL ON ( CTA_ARTICULO2.ID_CTA_ARTICULO = V_TN_SALDOS_STOCK_CENTRAL.ID_CTA_ARTICULO  AND CTA_DEPOSITO2.ID_CTA_DEPOSITO = V_TN_SALDOS_STOCK_CENTRAL.ID_CTA_DEPOSITO  AND  SUCURSAL2.ID_SUCURSAL = V_TN_SALDOS_STOCK_CENTRAL.ID_SUCURSAL)


WHERE 

CTA03.Cod_Articu NOT IN ('Art. Ajuste') AND (CTA03.Cod_Articu <> '') AND CTA02.T_COMP <> 'REC'
 AND 
 ((isnull(CTA03.RENGL_PADR,0) = 0) OR (isnull(CTA03.INSUMO_KIT_SEPARADO,0) = 1))

 and MONTH(CTA03.FECHA_MOV) = MONTH(GETDATE())

GROUP BY 
	CASE WHEN PROVEEDOR_HABITUAL_ART.COD_PROVEE IS NULL THEN    CPA01.NOM_PROVEE ELSE CPA01_PROV_HABITUAL.NOM_PROVEE END , CASE WHEN PROVEEDOR_HABITUAL_ART.COD_PROVEE IS NULL THEN    ISNULL(PROVEEDOR_ART.COD_PROVEE, '' ) ELSE PROVEEDOR_HABITUAL_ART.COD_PROVEE END
	)

