--SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
--SET DATEFORMAT DMY 
--SET DATEFIRST 7 
--SET DEADLOCK_PRIORITY -8;
--Select * from VentasXMarcaMensual

CREATE View VentasXMarcaMensual AS 
WITH ClasificacionRecursiva AS ( --Esa subconsulta lo que hace es traer las carpetas padre de cada subcarpeta.
    SELECT 
        IDFOLDER,
        IDPARENT,
        1 AS Nivel
    FROM 
        DISTRIBUIDORA_FRANCO..STA11FLD
    WHERE 
        IDFOLDER IN (
            SELECT TOP 1 IDFOLDER
            FROM DISTRIBUIDORA_FRANCO..STA11ITC A
            --WHERE A.CODEA = CTA_ARTICULO.COD_ARTICULO
        )
    UNION ALL
    SELECT 
        F.IDFOLDER,
        F.IDPARENT,
        CR.Nivel + 1
    FROM 
        DISTRIBUIDORA_FRANCO..STA11FLD F
    INNER JOIN ClasificacionRecursiva CR ON F.IDPARENT = CR.IDFOLDER
)

SELECT 
	CTA_ARTICULO.DESC_ADICIONAL_ARTICULO AS [Desc. Adicional] ,
	SUM( CASE WHEN CTA02.TCOMP_IN_V = 'CC' then (-1) ELSE (1) END *  CASE 'BIMONCTE' WHEN 'BIMONCTE' THEN   (CASE CTA02.MON_CTE WHEN 1 THEN CASE 'NO' WHEN 'NO'     
	THEN (CTA03.PRECIO_NET * CTA03.CANTIDAD)                                    ELSE CASE CTA02.IMPORTE WHEN 0 THEN (CTA03.PRECIO_NET * CTA03.CANTIDAD)                                        ELSE ((CTA03.PRECIO_NET * CTA03.CANTIDAD) - ((CTA03.PRECIO_NET * CTA03.CANTIDAD) * CTA02.PORC_BONIF/100) +                                        ((CTA03.PRECIO_NET * CTA03.CANTIDAD) * (CTA02.IMPORTE_FL/(CTA02.IMPORTE-CTA02.IMPORTE_FL+CTA02.IMPORTE_BO-CTA02.IMPORTE_IV-CTA02.IMPORTE_IN-ISNULL(IMPUESTOS.IMPORTE,0)))) + ((CTA03.PRECIO_NET * CTA03.CANTIDAD)                                        * CTA02.PORC_RECARGO/100))  END END                                  ELSE CASE 'NO' WHEN 'NO'                                   THEN (CTA03.PRECIO_NET * CTA03.CANTIDAD) * CTA02.COTIZ                                     ELSE CASE CTA02.IMPORTE WHEN 0 THEN (CTA03.PRECIO_NET * CTA03.CANTIDAD) * CTA02.COTIZ                                        ELSE ((CTA03.PRECIO_NET * CTA03.CANTIDAD) - ((CTA03.PRECIO_NET * CTA03.CANTIDAD) * CTA02.PORC_BONIF/100) +                                        ((CTA03.PRECIO_NET * CTA03.CANTIDAD) * (CTA02.IMPORTE_FL/(CTA02.IMPORTE-CTA02.IMPORTE_FL+CTA02.IMPORTE_BO-CTA02.IMPORTE_IV-CTA02.IMPORTE_IN-ISNULL(IMPUESTOS.IMPORTE,0)))) + ((CTA03.PRECIO_NET * CTA03.CANTIDAD)                                        * CTA02.PORC_RECARGO/100))  * CTA02.COTIZ END END                             END)  WHEN 'BIORIGEN' THEN   (CASE CTA02.MON_CTE WHEN 1 THEN CASE CTA02.COTIZ WHEN 0                                   THEN 0                                   ELSE CASE 'NO' WHEN 'NO'                                        THEN (CTA03.PRECIO_NET * CTA03.CANTIDAD)   / CTA02.COTIZ                                         ELSE CASE CTA02.IMPORTE WHEN 0 THEN (CTA03.PRECIO_NET * CTA03.CANTIDAD)/ CTA02.COTIZ                                              ELSE ((CTA03.PRECIO_NET * CTA03.CANTIDAD) - ((CTA03.PRECIO_NET * CTA03.CANTIDAD) * CTA02.PORC_BONIF/100) +                                                           ((CTA03.PRECIO_NET * CTA03.CANTIDAD) * (CTA02.IMPORTE_FL/(CTA02.IMPORTE-CTA02.IMPORTE_FL+CTA02.IMPORTE_BO-CTA02.IMPORTE_IV-CTA02.IMPORTE_IN-ISNULL(IMPUESTOS.IMPORTE,0))))                                                           + ((CTA03.PRECIO_NET * CTA03.CANTIDAD) * CTA02.PORC_RECARGO/100))  / CTA02.COTIZ END END                                        END                                   ELSE CASE 'NO' WHEN 'NO'                                   THEN (CTA03.PRECIO_NET * CTA03.CANTIDAD)                                    ELSE CASE CTA02.IMPORTE WHEN 0 THEN (CTA03.PRECIO_NET * CTA03.CANTIDAD)                                        ELSE ((CTA03.PRECIO_NET * CTA03.CANTIDAD) - ((CTA03.PRECIO_NET * CTA03.CANTIDAD) * CTA02.PORC_BONIF/100) +                                                           ((CTA03.PRECIO_NET * CTA03.CANTIDAD) * (CTA02.IMPORTE_FL/(CTA02.IMPORTE-CTA02.IMPORTE_FL+CTA02.IMPORTE_BO-CTA02.IMPORTE_IV-CTA02.IMPORTE_IN-ISNULL(IMPUESTOS.IMPORTE,0)))) +                                                           ((CTA03.PRECIO_NET * CTA03.CANTIDAD) * CTA02.PORC_RECARGO/100))  END END                              END)  WHEN 'BICOTIZ'  THEN CASE 1  WHEN 0 THEN 0  ELSE   (CASE CTA02.MON_CTE WHEN 1 THEN CASE 'NO' WHEN 'NO'                                THEN (CTA03.PRECIO_NET * CTA03.CANTIDAD)  / 1                                ELSE CASE CTA02.IMPORTE WHEN 0 THEN (CTA03.PRECIO_NET * CTA03.CANTIDAD)  / 1                                      ELSE ((CTA03.PRECIO_NET * CTA03.CANTIDAD) - ((CTA03.PRECIO_NET * CTA03.CANTIDAD) * CTA02.PORC_BONIF/100) +                                     ((CTA03.PRECIO_NET * CTA03.CANTIDAD) * (CTA02.IMPORTE_FL/(CTA02.IMPORTE-CTA02.IMPORTE_FL+CTA02.IMPORTE_BO-CTA02.IMPORTE_IV-CTA02.IMPORTE_IN-ISNULL(IMPUESTOS.IMPORTE,0)))) +                                     ((CTA03.PRECIO_NET * CTA03.CANTIDAD) * CTA02.PORC_RECARGO/100))                                                           / 1 END END                             ELSE CASE 'NO' WHEN 'NO'                              THEN (CTA03.PRECIO_NET * CTA03.CANTIDAD) * CTA02.COTIZ  / 1                                ELSE CASE CTA02.IMPORTE WHEN 0 THEN  (CTA03.PRECIO_NET * CTA03.CANTIDAD) * CTA02.COTIZ  / 1                                     ELSE ((CTA03.PRECIO_NET * CTA03.CANTIDAD) - ((CTA03.PRECIO_NET * CTA03.CANTIDAD) * CTA02.PORC_BONIF/100) +                                             ((CTA03.PRECIO_NET * CTA03.CANTIDAD) * (CTA02.IMPORTE_FL/(CTA02.IMPORTE-CTA02.IMPORTE_FL+CTA02.IMPORTE_BO-CTA02.IMPORTE_IV-CTA02.IMPORTE_IN-ISNULL(IMPUESTOS.IMPORTE,0)))) +                                              ((CTA03.PRECIO_NET * CTA03.CANTIDAD) * CTA02.PORC_RECARGO/100)) * CTA02.COTIZ  / 1   END END                              END)  END END      )  AS [Importe], 
		(
		SELECT 
			CASE 
				WHEN MAX(CR.IDPARENT) = 2 THEN 'Ferreteria' 
				WHEN MAX(CR.IDPARENT) = 3 THEN 'Alimentos' 
				ELSE 'Otra clasificación' 
			END
		FROM 
			ClasificacionRecursiva CR
	) AS [Clasificación]
FROM 
CTA03 (NOLOCK)  
INNER JOIN CTA02 (NOLOCK) ON 
(CTA02.N_COMP = CTA03.N_COMP AND CTA02.T_COMP = CTA03.T_COMP AND CTA03.NRO_SUCURS = CTA02.NRO_SUCURS)
 
LEFT JOIN CTA_ARTICULO (NOLOCK) ON 
CTA03.Cod_Articu = CTA_ARTICULO.Cod_Articulo

LEFT JOIN(SELECT  NRO_SUCURS, T_COMP, N_COMP, SUM(IMPORTE) AS IMPORTE           FROM CTA04           WHERE (COD_IMPUES <>'') OR ( (COD_ALICUO BETWEEN 21 AND 80 ) OR COD_ALICUO = 82)           GROUP BY NRO_SUCURS, T_COMP, N_COMP) AS IMPUESTOS ON IMPUESTOS.T_COMP= CTA02.T_COMP AND IMPUESTOS.N_COMP = CTA02.N_COMP AND IMPUESTOS.NRO_SUCURS= CTA02.NRO_SUCURS 
 
LEFT JOIN CTA_ARTICULO (NOLOCK) CTA_ARTICULO2 ON CTA03.COD_ARTICU = CTA_ARTICULO2.COD_ARTICULO  
LEFT JOIN SUCURSAL (NOLOCK) SUCURSAL2 ON CTA03.NRO_SUCURS = SUCURSAL2.NRO_SUCURSAL  
LEFT JOIN CTA_DEPOSITO (NOLOCK) CTA_DEPOSITO2 ON CTA03.COD_DEPOSI = CTA_DEPOSITO2.COD_CTA_DEPOSITO  
LEFT JOIN  V_TN_SALDOS_STOCK_CENTRAL ON ( CTA_ARTICULO2.ID_CTA_ARTICULO = V_TN_SALDOS_STOCK_CENTRAL.ID_CTA_ARTICULO  AND CTA_DEPOSITO2.ID_CTA_DEPOSITO = V_TN_SALDOS_STOCK_CENTRAL.ID_CTA_DEPOSITO  AND  SUCURSAL2.ID_SUCURSAL = V_TN_SALDOS_STOCK_CENTRAL.ID_SUCURSAL)
LEFT JOIN DISTRIBUIDORA_FRANCO..STA11ITC C ON C.CODEA = CTA_ARTICULO.COD_ARTICULO
LEFT JOIN DISTRIBUIDORA_FRANCO..STA11FLD D ON D.IDFOLDER = C.IDFOLDER

WHERE 

CTA03.Cod_Articu NOT IN ('Art. Ajuste') AND (CTA03.Cod_Articu <> '') AND CTA02.T_COMP <> 'REC'
AND ((isnull(CTA03.RENGL_PADR,0) = 0) OR (isnull(CTA03.INSUMO_KIT_SEPARADO,0) = 1))
AND MONTH(CTA03.FECHA_MOV) = MONTH(GETDATE())

GROUP BY 
	 CTA_ARTICULO.DESC_ADICIONAL_ARTICULO
