CREATE VIEW UnidadesXCantidad AS 
WITH ClasificacionRecursiva AS ( --Esa subconsulta lo que hace es traer las carpetas padre de cada subcarpeta.
    SELECT 
        IDFOLDER,
        IDPARENT,
        1 AS Nivel
    FROM 
        DISTRIBUIDORA_FRANCO..STA11FLD
    WHERE 
        IDFOLDER IN (
            SELECT TOP 1 IDFOLDER
            FROM DISTRIBUIDORA_FRANCO..STA11ITC A
            --WHERE A.CODEA = CTA_ARTICULO.COD_ARTICULO
        )
    UNION ALL
    SELECT 
        F.IDFOLDER,
        F.IDPARENT,
        CR.Nivel + 1
    FROM 
        DISTRIBUIDORA_FRANCO..STA11FLD F
    INNER JOIN ClasificacionRecursiva CR ON F.IDPARENT = CR.IDFOLDER
)
SELECT 
	CTA03.FECHA_MOV AS [Fecha Movimiento],
	CTA_ARTICULO.COD_ARTICULO AS [Cód. Artículo] ,
	CTA_ARTICULO.DESC_CTA_ARTICULO AS [Descripción] ,
	CTA03.NRO_SUCURS AS [Nro. Sucursal] ,
	SUCURSAL.DESC_SUCURSAL AS [Desc. sucursal] ,
	(
		SELECT 
			CASE 
				WHEN MAX(CR.IDPARENT) = 2 THEN 'Ferreteria' 
				WHEN MAX(CR.IDPARENT) = 3 THEN 'Alimentos' 
				ELSE 'Otra clasificación' 
			END
		FROM 
			ClasificacionRecursiva CR
	) AS [Clasificación],
	SUM(
		CASE CTA03.TCOMP_IN_V  
			WHEN 'CC' THEN (-1)    
			ELSE (1)  
		END  * CTA03.CANTIDAD
	) AS [Cantidad] 
FROM 
	CTA03 
	INNER JOIN CTA_ARTICULO ON CTA_ARTICULO.COD_ARTICULO = CTA03.COD_ARTICU 
	INNER JOIN SUCURSAL ON SUCURSAL.NRO_SUCURSAL = CTA03.NRO_SUCURS 
	LEFT JOIN CTA_DEPOSITO ON CTA_DEPOSITO.COD_CTA_DEPOSITO = CTA03.COD_DEPOSI 
	INNER JOIN CTA02 ON CTA03.NRO_SUCURS=CTA02.NRO_SUCURS AND CTA03.T_COMP = CTA02.T_COMP AND CTA03.N_COMP = CTA02.N_COMP	
	LEFT JOIN STA16 ON 1=1	
	LEFT JOIN STA29 FAMILIA_ART ON SUBSTRING(CTA_ARTICULO.COD_ARTICULO, 1, LONG_FAM_A) = FAMILIA_ART.COD_AGR	
	LEFT JOIN STA29 GRUPO_ART ON SUBSTRING(CTA_ARTICULO.COD_ARTICULO, 0, LONG_FAM_A+LONG_GRU_A+1) = GRUPO_ART.COD_AGR	
	LEFT JOIN (SELECT COD_ARTICULO, DESC_CTA_ARTICULO FROM CTA_ARTICULO WHERE USA_ESC = 'B') AS BASE ON (BASE.COD_ARTICULO = CTA_ARTICULO.BASE) 
	LEFT JOIN DISTRIBUIDORA_FRANCO..STA11ITC A ON A.CODEA = CTA_ARTICULO.COD_ARTICULO
	LEFT JOIN DISTRIBUIDORA_FRANCO..STA11FLD B ON B.IDFOLDER = A.IDFOLDER
WHERE 
	(CTA02.T_COMP <> 'REC')
	AND (
		(isnull(CTA03.RENGL_PADR,0) = 0) OR 
		(isnull(CTA03.INSUMO_KIT_SEPARADO,0) = 1)
	)
GROUP BY 
	CTA_ARTICULO.COD_ARTICULO , 
	CTA_ARTICULO.DESC_CTA_ARTICULO , 
	CTA03.NRO_SUCURS , 
	SUCURSAL.DESC_SUCURSAL , 
	CTA03.FECHA_MOV ;

