/*CREA LA TABLA DE AUDITORIA*/

CREATE TABLE AUDI_GVA09
(	ID_AUDI UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
	ID_GVA09 INT,
	N_COTIZ VARCHAR(14),
	COD_ARTICU VARCHAR(15),
	PRECIO DECIMAL(13),
	PRECIO_LISTA DECIMAL(13),
	TERMINAL_MODIFICACION_PRECIO VARCHAR(1000),
	USUARIO_MODIFICACION_PRECIO VARCHAR(1000),
	FECHA_MODIFICACION_PRECIO DATETIME,
	ABM VARCHAR(MAX))
ALTER TABLE AUDI_GVA09 ADD CONSTRAINT PK_AUDIT PRIMARY KEY (ID_AUDI)

-----------------------------------UPDATE-------------------------------------------------

CREATE TRIGGER TR_TRIGGER_AUDIT_UPD ON GVA09
FOR UPDATE
AS
INSERT INTO AUDI_GVA09 (
    ID_GVA09,
    N_COTIZ,
    COD_ARTICU,
    PRECIO,
    PRECIO_LISTA,
    TERMINAL_MODIFICACION_PRECIO,
    USUARIO_MODIFICACION_PRECIO,
    FECHA_MODIFICACION_PRECIO,
    ABM
)
SELECT
    I.ID_GVA09,
    I.N_COTIZ,
    I.COD_ARTICU,
    I.PRECIO,
    I.PRECIO_LISTA,
    HOST_NAME(),
    SUSER_SNAME(),
    GETDATE(),
    'UPDATE'
FROM
    INSERTED I WITH (NOLOCK);
GO


-----------------------------------ALTA---------------------------------------------------
CREATE TRIGGER TR_TRIGGER_AUDIT_ALT ON GVA09
FOR INSERT
AS
INSERT INTO AUDI_GVA09 (
    ID_GVA09,
    N_COTIZ,
    COD_ARTICU,
    PRECIO,
    PRECIO_LISTA,
    TERMINAL_MODIFICACION_PRECIO,
    USUARIO_MODIFICACION_PRECIO,
    FECHA_MODIFICACION_PRECIO,
    ABM
)
SELECT
    I.ID_GVA09,
    I.N_COTIZ,
    I.COD_ARTICU,
    I.PRECIO,
    I.PRECIO_LISTA,
    HOST_NAME(),
    SUSER_SNAME(),
    GETDATE(),
    'UPDATE'
FROM
    INSERTED I WITH (NOLOCK);
GO
