SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET DATEFORMAT DMY 
SET DATEFIRST 7 
SET DEADLOCK_PRIORITY -8;
SELECT 
    GVA12.Cod_client AS [Cód. cliente],
    CASE GVA12.COD_CLIENT WHEN '000000' THEN 'OCASIONAL' ELSE GVA14.RAZON_SOCI END AS [Razón social],
    GVA12.T_COMP AS [Tipo comprobante],
    GVA12.N_COMP AS [Nro. comprobante],
    STA11.COD_ARTICU AS [Cod. Artículo],
    STA11.DESCRIPCIO AS [Descripcion],
    Campos.CodigoAnterior AS [Código Anterior],
    GVA12.FECHA_EMIS AS [Fecha de emisión],
    CASE GVA12.DOC_ELECTR WHEN 1 THEN 'Si' ELSE 'No' END AS [Doc. Electrónico],
    SUM(CASE Gva12.TComp_In_V WHEN 'CC' THEN (-1) ELSE 1 END * Gva53.Faltan_Rem * (CASE GVA12.MON_CTE WHEN 1 THEN GVA53.PRECIO_NET ELSE (GVA53.PRECIO_NET * GVA12.Cotiz) END)) AS [Total Pendiente] 
FROM 
GVA12 
INNER JOIN GVA53 ON GVA12.N_COMP = Gva53.N_Comp AND GVA12.T_COMP = Gva53.T_Comp 
LEFT JOIN GVA81 ON GVA81.COD_CLASIF = GVA12.COD_CLASIF 
LEFT JOIN GVA14 ON GVA12.COD_CLIENT <> '000000' AND GVA14.COD_CLIENT = GVA12.COD_CLIENT 
LEFT JOIN GVA38 ON GVA12.COD_CLIENT = '000000' AND GVA38.T_COMP = GVA12.T_COMP AND GVA38.N_COMP = GVA12.N_COMP 
LEFT JOIN GVA18 ON (GVA12.COD_CLIENT <> '000000' AND GVA14.COD_PROVIN = GVA18.COD_PROVIN) OR (GVA12.COD_CLIENT = '000000' AND GVA38.COD_PROVIN = GVA18.COD_PROVIN) 
LEFT JOIN GVA133 ON GVA18.COD_PAIS = GVA133.COD_PAIS 
LEFT JOIN GVA43 ON GVA12.TALONARIO = Gva43.Talonario 
LEFT JOIN GVA23 ON Gva12.Cod_vended = GVA23.COD_VENDED 
LEFT JOIN GVA05 ON GVA14.COD_ZONA = GVA05.COD_ZONA 
LEFT JOIN GVA24 ON GVA12.COD_TRANSP = GVA24.COD_TRANSP 
INNER JOIN STA22 ON GVA12.COD_SUCURS  = STA22.COD_SUCURS 
LEFT JOIN DIRECCION_ENTREGA ON DIRECCION_ENTREGA.ID_DIRECCION_ENTREGA = GVA12.ID_DIRECCION_ENTREGA 
LEFT JOIN GVA14 CLIENTE_ENTREGA_HABITUAL ON CLIENTE_ENTREGA_HABITUAL.COD_CLIENT = GVA12.COD_CLIENT 
LEFT JOIN DIRECCION_ENTREGA DIR_ENTREGA_HABITUAL ON CLIENTE_ENTREGA_HABITUAL.COD_GVA14 = DIR_ENTREGA_HABITUAL.COD_CLIENTE AND DIR_ENTREGA_HABITUAL.HABITUAL = 'S' 
LEFT JOIN GVA18 PROV_ENTREGA_HABITUAL ON DIR_ENTREGA_HABITUAL.COD_PROVINCIA = PROV_ENTREGA_HABITUAL.COD_GVA18 
LEFT JOIN DIRECCION_ENTREGA DIRECCION ON GVA12.ID_DIRECCION_ENTREGA = DIRECCION.ID_DIRECCION_ENTREGA 
LEFT JOIN GVA18 PROV_ENTREGA ON DIRECCION.COD_PROVINCIA = PROV_ENTREGA.COD_GVA18 
LEFT JOIN GVA38 OCASIONALES ON OCASIONALES.T_COMP = GVA12.T_COMP AND OCASIONALES.N_COMP = GVA12.N_COMP 
LEFT JOIN GVA18 PROV_OCASIONALES ON OCASIONALES.COD_PROVINCIA_ENTREGA = PROV_OCASIONALES.COD_PROVIN
JOIN STA11 ON STA11.COD_ARTICU = GVA53.COD_ARTICU
  OUTER APPLY (
        SELECT 
            STA11.CAMPOS_ADICIONALES.value('(/CAMPOS_ADICIONALES/CA_CDIGO_SISTEMA_ORIGINAL)[1]', 'nvarchar(max)') AS CodigoAnterior
    ) AS Campos

Where GVA12.ESTADO_STK ='P'  AND GVA53.T_COMP = 'FAC'	 AND	(GVA53.Faltan_Rem <> 0)  AND (       (GVA53.COD_ARTICU <> GVA53.COD_ARTICU_KIT)       OR       (GVA53.COD_ARTICU_KIT IS NULL)      )

GROUP BY 
	GVA12.Cod_client , CASE GVA12.COD_CLIENT WHEN '000000' THEN 'OCASIONAL' ELSE GVA14.RAZON_SOCI END , 
	GVA12.T_COMP , GVA12.N_COMP , GVA12.FECHA_EMIS, CASE GVA12.DOC_ELECTR WHEN 1 THEN 'Si' ELSE 'No' END  , 
	GVA12.N_COMP, STA11.COD_ARTICU, STA11.DESCRIPCIO, Campos.CodigoAnterior







